const mockEvents = [
  // --- PROTESTS ---
  {
    category: "Protests",
    subcategory: "Peaceful protest",
    date: "2026-07-02",
    country: "Israel",
    title: "Israel protests demand probe after October 7 security failures as Hamas attack marked",
    actor: "Protesters",
    goldstein: -6.5,
    mag: 0.0,
    sig: 0.22,
    lat: 31.0,
    lng: 35.0,
  },
  {
    category: "Protests",
    subcategory: "Peaceful protest",
    date: "2026-07-02",
    country: "Pakistan",
    title: "PoK leader claims Pakistan Army armed Kashmiris amid Rawalakot protests",
    actor: "Protesters",
    goldstein: -6.5,
    mag: 0.0,
    sig: 0.22,
    lat: 30.4,
    lng: 73.1,
  },
  {
    category: "Protests",
    subcategory: "Protest with intervention",
    date: "2026-07-01",
    country: "Peru",
    title: "Protest blockade cuts water to Ilo after Tacna communeros block Ite intake",
    actor: "Communeros of Cambaya, Coraguaya, Camilaca, Vilalaca and Santa Cruz",
    goldstein: -7.5,
    mag: 0.0,
    sig: 0.24,
    lat: -9.19,
    lng: -75.02,
  },
  {
    category: "Protests",
    subcategory: "Protest with violent opposition",
    date: "2026-07-03",
    country: "Colombia",
    title: "Student demonstrations spark localized clashes with security forces in Bogotá hub",
    actor: "University Students",
    goldstein: -8.0,
    mag: 0.1,
    sig: 0.28,
    lat: 4.6097,
    lng: -74.0817,
  },
  {
    category: "Protests",
    subcategory: "Labor Demonstration",
    date: "2026-07-03",
    country: "Greece",
    title: "Port workers organize 24-hour rally in Athens over supply chain logistics disputes",
    actor: "Maritime Union",
    goldstein: -4.2,
    mag: 0.0,
    sig: 0.19,
    lat: 37.9838,
    lng: 23.7275,
  },

  // --- BATTLES ---
  {
    category: "Battles",
    subcategory: "Armed clash",
    date: "2026-07-03",
    country: "Ukraine",
    title: "Heavy structural skirmishes reported along eastern sectors near Kharkiv perimeter",
    actor: "Military Forces",
    goldstein: -10.0,
    mag: 0.4,
    sig: 0.45,
    lat: 49.9935,
    lng: 36.2304,
  },
  {
    category: "Battles",
    subcategory: "Militia skirmish",
    date: "2026-07-02",
    country: "Democratic Republic of the Congo",
    title: "Clashes erupt between regional coalition forces and rebel factions in North Kivu area",
    actor: "Armed Coalition",
    goldstein: -9.5,
    mag: 0.3,
    sig: 0.38,
    lat: -1.6585,
    lng: 29.2205,
  },
  {
    category: "Battles",
    subcategory: "Insurgent ambush",
    date: "2026-07-02",
    country: "Myanmar",
    title: "Local defense groups engage state patrol unit in coordinated rural highway ambush",
    actor: "Resistance Factions",
    goldstein: -9.0,
    mag: 0.2,
    sig: 0.34,
    lat: 21.9162,
    lng: 95.9560,
  },
  {
    category: "Battles",
    subcategory: "Border skirmish",
    date: "2026-07-01",
    country: "Sudan",
    title: "Territorial skirmishes intensify along active gridlines south of Khartoum hub",
    actor: "Paramilitary Units",
    goldstein: -10.0,
    mag: 0.5,
    sig: 0.51,
    lat: 15.5007,
    lng: 32.5599,
  },

  // --- EXPLOSIONS/REMOTE VIOLENCE ---
  {
    category: "Explosions/Remote violence",
    subcategory: "Drone strike",
    date: "2026-07-03",
    country: "Yemen",
    title: "Remote drone tracking systems register targeted facility strikes near Red Sea docks",
    actor: "Unidentified Drone Wing",
    goldstein: -9.0,
    mag: 0.3,
    sig: 0.41,
    lat: 14.7979,
    lng: 42.9545,
  },
  {
    category: "Explosions/Remote violence",
    subcategory: "Improvised explosive device",
    date: "2026-07-02",
    country: "Somalia",
    title: "Roadside device detonates near security convoy checkpoint outside Mogadishu parameters",
    actor: "Insurgent Network",
    goldstein: -8.5,
    mag: 0.2,
    sig: 0.37,
    lat: 2.0469,
    lng: 45.3182,
  },
  {
    category: "Explosions/Remote violence",
    subcategory: "Missile interception",
    date: "2026-07-02",
    country: "Syria",
    title: "Air defense architecture intercepts incoming low-altitude missile vectors near western airspace",
    actor: "Air Defense Unit",
    goldstein: -9.0,
    mag: 0.4,
    sig: 0.42,
    lat: 34.8021,
    lng: 38.9968,
  },
  {
    category: "Explosions/Remote violence",
    subcategory: "Artillery bombardment",
    date: "2026-07-01",
    country: "Lebanon",
    title: "Remote artillery shelling reported across southern border sectors causing landscape damage",
    actor: "Artillery Battery",
    goldstein: -9.5,
    mag: 0.5,
    sig: 0.48,
    lat: 33.3153,
    lng: 35.3516,
  }
];

export default mockEvents;